#pragma once

#include "../../Port/config.h"
#include "CommDef.h"

#ifdef WIN32
#if defined( GAMENETCOMMON_EXPORTS )
	#define GAMENETCOMMON_INTERFACE		DLL_EXPORT
	#define GAMENETCOMMON_CLASS			DLL_CLASS_EXPORT
	#define GAMENETCOMMON_GLOBAL		DLL_GLOBAL_EXPORT
#else
	#define GAMENETCOMMON_INTERFACE		DLL_IMPORT
	#define GAMENETCOMMON_CLASS			DLL_CLASS_IMPORT
	#define GAMENETCOMMON_GLOBAL		DLL_GLOBAL_IMPORT
#endif//#if defined(GFX_EXPORTS)

#else
	#define GAMENETCOMMON_INTERFACE		
	#define GAMENETCOMMON_CLASS	
	#define GAMENETCOMMON_GLOBAL		
#endif
